fix indentation

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,194 +1,297 @@
-cleanup:
-  docker: null
-  steps:
-  - run: {command: '# your code here
+version: 2.1
 
-        export OldWorkflowID="the id here"
-
-        export STACKS=[] #put the list of stacks here
-
-        ', name: Get old stack workflow id}
-  - run: {command: "if [[ \"${STACKS[@]}\" =~ \"${OldWorkflowID}\" ]]\nthen\n  # your\
-        \ code here\nfi\n", name: Remove old stacks and files}
 commands:
   destroy-environment:
-    description: Destroy back-end and front-end cloudformation stacks given a workflow
-      ID.
-    parameters: null
+    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
+    parameters:
+      # Add parameter here   
     steps:
-    - run: {command: '# Your code here
+      - run:
+          name: Destroy environments
+          when: on_fail
+          command: |
+            # Your code here
+            exit 1
 
-          exit 1
-
-          ', name: Destroy environments, when: on_fail}
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
-    parameters: null
+    parameters:
+      # Add parameter here     
     steps:
-    - run: {command: "# Curl command here to see if there was a successful migration\
-          \ associated with the workflow id, store result in SUCCESS variable\nSUCCESS\
-          \ = 1\nif(( $SUCCESS==1 )); \nthen\n#  cd ~/project/backend\n#  npm install\n\
-          #  Add revert code here. You can find this in the Getting Started section.\n\
-          \  exit 1\nfi\n", name: Revert migrations}
+      - run:
+          name: Revert migrations
+          # Add when this will run
+          command: |
+            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            SUCCESS = 1
+            if(( $SUCCESS==1 )); 
+            then
+            #  cd ~/project/backend
+            #  npm install
+            #  Add revert code here. You can find this in the Getting Started section.
+              exit 1
+            fi
+            
 jobs:
-  build-backend:
-    docker:
-    - {image: 'circleci/node:13.8.0'}
-    steps:
-    - checkout
-    - restore_cache:
-        keys: [backend-build]
-    - run: {command: 'npm run build
-
-          exit 1
-
-          ', name: Back-end build}
-    - save_cache:
-        key: backend-build
-        paths: [backend/node_modules]
   build-frontend:
     docker:
-    - {image: 'circleci/node:13.8.0'}
+      - image: circleci/node:13.8.0
     steps:
-    - checkout
-    - restore_cache:
-        keys: [frontend-build]
-    - run: {command: 'npm run build
+      - checkout
+      - restore_cache:
+          keys: [frontend-build]
+      - run:
+          name: Build front-end
+          command: |
+            npm run build
+            exit 1
+      - save_cache:
+          paths: [frontend/node_modules]
+          key: frontend-build
 
-          exit 1
-
-          ', name: Build front-end}
-    - save_cache:
-        key: frontend-build
-        paths: [frontend/node_modules]
-  cloudfront-update:
-    docker: null
+  build-backend:
+    docker:
+      - image: circleci/node:13.8.0
     steps:
-    - run: {command: '# your code here
+      - checkout
+      - restore_cache:
+          keys: [backend-build]
+      - run:
+          name: Back-end build
+          command: |
+             npm run build
+             exit 1
+      - save_cache:
+          paths: [backend/node_modules]
+          key: backend-build
 
-          ', name: Install dependencies}
-    - run: {command: '# your code here
-
-          ', name: Update cloudfront distribution}
-  configure-infrastructure:
-    docker: null
+  test-frontend:
+    docker:
+      # Docker image here
     steps:
-    - run: {command: '# Your code here
-
-          exit 1
-
-          ', name: Install dependencies}
-    - run: {command: '# Your code here
-
-          exit 1
-
-          ', name: Configure server}
-  deploy-backend:
-    docker: null
+      # Checkout code from git
+      # Restore from cache
+      # Your job code here
+                
+  test-backend:
+    docker:
+      # Docker image here
     steps:
-    - run: {command: '# your code here
-
-          ', name: Install dependencies}
-    - run: {command: '# your code here
-
-          ', name: Deploy backend}
-  deploy-frontend:
-    docker: null
+      # Checkout code from git
+      # Restore from cache
+      # Your job code here
+            
+  scan-frontend:
+    docker:
+      # Docker image here
     steps:
-    - run: {command: '# your code here
+      # Checkout code from git
+      # Restore from cache
+      # Your job code here
 
-          ', name: Install dependencies}
-    - run: {command: '# your code here
+  scan-backend:
+    docker:
+      # Docker image here
+    steps:
+      # Checkout code from git
+      # Restore from cache
+      # Your job code here
 
-          export API_URL="http://${BACKEND_IP}:3030"
-
-          echo "${API_URL}"
-
-          ', name: Get backend url}
-    - run: {command: '# your code here
-
-          ', name: Deploy frontend objects}
   deploy-infrastructure:
-    docker: null
+    docker:
+      # Docker image here that supports AWS CLI
     steps:
-    - run: {command: "aws cloudformation deploy \\\n  --template-file .circleci/files/backend.yml\
-          \ \\\n  #--tags project=your-tag \\\n  # --stack-name \"your back-end stack\
-          \ name with workflow id\" \\\n  # --parameter-overrides ID=\"your workflow\
-          \ id\"  \n  exit 1\n", name: Ensure back-end infrastructure exists}
-    - run: {command: "aws cloudformation deploy \\\n  --template-file .circleci/files/frontend.yml\
-          \ \\\n  #--tags project=your-tag \\\n  # --stack-name \"your front-end stack\
-          \ name with workflow id\" \\\n  # --parameter-overrides ID=\"your workflow\
-          \ id\"  \n  exit 1\n", name: Ensure front-end infrastructure exist}
-    - run: {command: '# Your code here
+      # Checkout code from git
+      - run:
+          name: Ensure back-end infrastructure exists
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/backend.yml \
+              #--tags project=your-tag \
+              # --stack-name "your back-end stack name with workflow id" \
+              # --parameter-overrides ID="your workflow id"  
+              exit 1
+      - run:
+          name: Ensure front-end infrastructure exist
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/frontend.yml \
+              #--tags project=your-tag \
+              # --stack-name "your front-end stack name with workflow id" \
+              # --parameter-overrides ID="your workflow id"  
+              exit 1
+      - run:
+          name: Add back-end ip to ansible inventory
+          command: |
+            # Your code here
+            exit 1
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/.circleci/ansible/inventory.txt
+      # Here's where you will add some code to rollback on failure      
 
-          exit 1
+  configure-infrastructure:
+    docker:
+      # Docker image here that supports Ansible
+    steps:
+      # Checkout code from git
+      # Add ssh keys with fingerprint
+      # attach workspace
+      - run:
+          name: Install dependencies
+          command: |
+            # Your code here
+            exit 1
+      - run:
+          name: Configure server
+          command: |
+            # Your code here
+            exit 1
+      # Here's where you will add some code to rollback on failure      
 
-          ', name: Add back-end ip to ansible inventory}
-    - persist_to_workspace:
-        paths: [project/.circleci/ansible/inventory.txt]
-        root: ~/
   run-migrations:
-    docker: null
+    docker:
+      # Docker image here that supports NodeJS
     steps:
-    - run: {command: '# Your code here
+      # Checkout code from git
+      - run:
+          name: Run migrations
+          command: |
+            # Your code here
+            exit 1
+      - run:
+          name: Send migration results to memstash
+          command: |
+            # Your code here
+            exit 1
+     # Here's where you will add some code to rollback on failure      
 
-          exit 1
+  deploy-frontend:
+    docker:
+      # Docker image here that supports AWS CLI
+    steps:
+      # Checkout code from git
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+      - run:
+          name: Get backend url
+          command: |
+            # your code here
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+      - run:
+          name: Deploy frontend objects
+          command: |
+            # your code here
+      # Here's where you will add some code to rollback on failure      
+                    
+  deploy-backend:
+    docker:
+      # Docker image here that supports Ansible
+    steps:
+      # Checkout code from git
+      # Add ssh keys with fingerprint
+      # attach workspace
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+      - run:
+          name: Deploy backend
+          command: |
+            # your code here
+      # Here's where you will add some code to rollback on failure  
 
-          ', name: Run migrations}
-    - run: {command: '# Your code here
-
-          exit 1
-
-          ', name: Send migration results to memstash}
-  scan-backend: {docker: null, steps: null}
-  scan-frontend: {docker: null, steps: null}
   smoke-test:
-    docker: null
+    docker:
+      # Lightweight Docker image 
     steps:
-    - run: {command: '# your code here
+      # Checkout code from git
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+      - run:
+          name: Get backend url
+          command: |
+            # your code here
+      - run:
+          name: Backend smoke test.
+          command: |
+            # your code here
+      - run:
+          name: Frontend smoke test.
+          command: |
+            # your code here
+      # Here's where you will add some code to rollback on failure  
 
-          ', name: Install dependencies}
-    - run: {command: '# your code here
+  cloudfront-update:
+    docker:
+      # Docker image here that supports AWS CLI
+    steps:
+      # Checkout code from git
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+      - run:
+          name: Update cloudfront distribution
+          command: |
+            # your code here
+      # Here's where you will add some code to rollback on failure  
 
-          ', name: Get backend url}
-    - run: {command: '# your code here
+cleanup:
+    docker:
+      # Docker image here
+    steps:
+      # Checkout code from git
+      - run:
+          name: Get old stack workflow id
+          command: |
+            # your code here
+            export OldWorkflowID="the id here"
+            export STACKS=[] #put the list of stacks here
+      - run:
+          name: Remove old stacks and files
+          command: |
+            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+            then
+              # your code here
+            fi
+            
 
-          ', name: Backend smoke test.}
-    - run: {command: '# your code here
-
-          ', name: Frontend smoke test.}
-  test-backend: {docker: null, steps: null}
-  test-frontend: {docker: null, steps: null}
-version: 2.1
 workflows:
   default:
     jobs:
-    - build-frontend
-    - build-backend
-    - test-frontend:
-        requires: [build-frontend]
-    - test-backend:
-        requires: [build-backend]
-    - scan-backend:
-        requires: [build-backend]
-    - scan-frontend:
-        requires: [build-frontend]
-    - deploy-infrastructure:
-        requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-      filters:
-        branches:
-          only: [test-feature-branch]
-    - configure-infrastructure:
-        requires: [deploy-infrastructure]
-    - run-migrations:
-        requires: [configure-infrastructure]
-    - deploy-frontend:
-        requires: [run-migrations]
-    - deploy-backend:
-        requires: [run-migrations]
-    - smoke-test:
-        requires: [deploy-backend, deploy-frontend]
-    - cloudfront-update:
-        requires: [smoke-test]
-    - cleanup:
-        requires: [cloudfront-update]
+      - build-frontend
+      - build-backend
+      # - test-frontend:
+      #    requires: [build-frontend]
+      # - test-backend:
+      #    requires: [build-backend]
+      # - scan-backend:
+      #    requires: [build-backend]
+      # - scan-frontend:
+      #    requires: [build-frontend]
+      # - deploy-infrastructure:
+      #    requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+      #   filters:
+      #     branches:
+      #       only: [test-feature-branch]
+      # - configure-infrastructure:
+      #    requires: [deploy-infrastructure]
+      # - run-migrations:
+      #    requires: [configure-infrastructure]
+      # - deploy-frontend:
+      #    requires: [run-migrations]
+      # - deploy-backend:
+      #    requires: [run-migrations]
+      # - smoke-test:
+      #    requires: [deploy-backend, deploy-frontend]
+      # - cloudfront-update:
+      #    requires: [smoke-test]
+      # - cleanup:
+      #    requires: [cloudfront-update]
